runtime: python39

handlers:
- url: /.*
  secure: always
  script: auto

automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: automatic
  min_pending_latency: 3000ms
  max_pending_latency: automatic

env_variables:
  apikey: "3cjXRGicq81c1uGfanYR3uguSBG6Gf7v"
  classi_password: "D=aSp4_oXIP"
  classi_username: "MahiroMiyake"
  linebot_token: "zSfrOcpGuUym36ZC+H1b/BulfwIbGLIIGy5Ysk/tBcci3/qdvymBStF1xx7/QxmPhEjcNHXEHuqWi/bd+voSnxCja8EwN4Z3IM3rrGcmRJThorc5RnwHJLadYY2D+DgXCtD28rO2n0z5x8UXwRnmpgdB04t89/1O/w1cDnyilFU="
  linebot_secret: "4220630ac88ec3a6d09f502f4bb5801e"
